# docker-compose up -d
services:
  db:
    image: postgres:12.8
    container_name: "${DB_CONTAINER_NAME:-postgres_db_dev}"
    environment:
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: "${POSTGRES_DB:-book-store-dev}"
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - db_data_dev:/var/lib/postgresql/data
    networks:
      - app_network
    restart: always

  gateway:
    build:
      context: ../go-store-gateway
      dockerfile: Dockerfile
    env_file:
      - .env.${ENV}
    container_name: "${GATEWAY_CONTAINER_NAME:-gateway_container}"
    ports:
      - "${GATEWAY_PORT:-8081}:8081"
    networks:
      - app_network
    restart: always

  book:
    build:
      context: ../go-store-services/book-service
      dockerfile: Dockerfile
    env_file:
      - .env.${ENV}
    container_name: "${BOOK_CONTAINER_NAME:-book_container}"
    depends_on:
      - db
    ports:
      - "${BOOK_PORT:-8082}:8082"
    networks:
      - app_network
    restart: always

volumes:
  db_data_dev:

networks:
  app_network:
